apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: argocd
type: Opaque
data:
  webhook-url: <BASE64-https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX>
