resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nodejs-express-mysql-configmap
    literals:
      - NODE_ENV=production
      - DATABASE_HOST=db-service
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password

secretGenerator:
  - name: nodejs-express-mysql-secret
    literals:
      - slack-webhook-url=https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
