apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-mysql
  labels:
    app: nodejs-express-mysql
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: nodejs-express-mysql
