apiVersion: v1
kind: Service
metadata:
  name: nodejs-express-mysql
spec:
  type: NodePort
  selector:
    app: nodejs-express-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
