apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-express-mysql.fullname" . }}-configmap
  labels:
    app: {{ include "nodejs-express-mysql.name" . }}
data:
  NODE_ENV: "{{ .Values.env.NODE_ENV }}"
  DATABASE_HOST: "db-service"
  DATABASE_USER: "admin"
  DATABASE_PASSWORD: "password"
