apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodejs-express-mysql.fullname" . }}-secret
  labels:
    app: {{ include "nodejs-express-mysql.name" . }}
type: Opaque
data:
  slack-webhook-url: {{ .Values.slackWebhookUrl | b64enc | quote }}
