apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-express.fullname" . }}
  labels:
    app: {{ include "nodejs-express.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "nodejs-express.name" . }}
