# Ortak namespace, override edilebilir
namespace: default

# Uygulama ile ilgili genel bilgiler
app:
  name: nodejs-express-mysql
  version: "1.0.0"

# Docker image ayarları
image:
  repository: hknsc/nodejs-express-mysql
  pullPolicy: IfNotPresent

# Log seviyeleri ve genel ortam değişkenleri
env:
  LOG_LEVEL: "info"
  NODE_ENV: "production"

# Kaynak limitleri ve talepler (tüm ortamlar için minimum gereksinim)
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Uygulama servisi ile ilgili ortak ayarlar
service:
  type: ClusterIP
  port: 80

# Ingress yapılandırması (varsayılan olarak kapalı, her ortamda açılabilir)
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "nodejs-express-mysql.local"
      paths:
        - "/"
  tls: []

# Otomatik ölçekleme için HPA ayarları (ortak değerler)
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Node seçici, tolerasyonlar ve affinity (varsayılan değerler)
nodeSelector: {}
tolerations: []
affinity: {}
