helmDefaults:
  tillerNamespace: kube-system
  kubeContext: default

values:
  - common-values.yaml

environments:
  dev:
    values:
      - environments/dev.yaml
  staging:
    values:
      - environments/staging.yaml
  prod:
    values:
      - environments/prod.yaml

repositories:
  - name: stable
    url: https://charts.helm.sh/stable

releases:
  - name: nodejs-express-mysql
    namespace: "{{ .Environment.Values.namespace }}"
    chart: ./charts/nodejs-express-mysql
    version: "1.0.0"
    values:
      - "{{ .Environment.Values }}"
  - name: rabbitmq
    namespace: monitoring
    chart: stable/rabbitmq
    values:
      - rabbitmq-values.yaml
