resources:
  - ../../base
  
configMapGenerator:
  - name: nodejs-express-mysql-configmap
    behavior: merge  # Çakışan ConfigMap'leri birleştirir
    literals:
      - NODE_ENV=production
      - DATABASE_HOST=prod-db-service
      - DATABASE_USER=prod-admin
      - DATABASE_PASSWORD=prod-password
