apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-notifications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bezkoder/nodejs-express-mysql.git'
    targetRevision: HEAD
    path: argocd/notifications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
