apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-mysql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hknisci/project_root'
    targetRevision: HEAD
    path: kustomization/overlays/prod  # Veya ilgili yol
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod  # Uygulamanın dağıtılacağı namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
