replicaCount: 1

image:
  repository: kbudde/rabbitmq-exporter
  tag: "v0.29.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9419

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi