name: Docker Image CI

# Main branch'e push yapıldığında pipeline çalışır
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub kullanıcı adınız
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub şifreniz

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true  # Docker image'i push eder
        tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-express-mysql:latest  # Docker image etiketi

    - name: Log out from Docker Hub
      run: docker logout
